### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by m-kashani** [shervindadashzade/karam#1]
## Todo:
- [ ] Perhaps add local storage saving
- [ ] Backend
- [ ] User login
- [ ] User register

**Comment by m-kashani** [comment]
@shervindadashzade 
من اینارو انجام میدم کامیت میکنم و لطفا مرج کن.

- [ ] بنده ریدمی رو تمیز میکنم یه تست میگیریم.
- [ ] لیست تو دو را میاریم اینجا که بتونیم به هم کامنت بدیم.
- [ ] نمایش گراف درونی فولدرها و توضیحاتشون تو ریدمی اضافه بشه و توضیحاتش بعنوان داکیومنت نوشته بشه.
